 
post_install() {
	glib-compile-schemas /usr/share/glib-2.0/schemas
    echo "GLib schemas compiled"

	\cp /etc/skel_mate/.xinitrc /etc/skel_new/.xinitrc
	
	\rm -rf /usr/share/mate-background-properties
    \rm -rf /usr/share/backgrounds/mate

    \mkdir -p /usr/share/mate-background-properties/

    \ln -s /usr/share/backgrounds/namib/config/mate-backgrounds.xml /usr/share/mate-background-properties/mate-backgrounds.xml
    \ln -s /usr/share/backgrounds/namib /usr/share/backgrounds/mate
}

post_upgrade() {
    post_install $1
}

pre_upgrade() {
    pre_install $1
}

post_remove() {
    \rm -rf /usr/share/mate-background-properties/
    \rm -rf /usr/share/backgrounds/mate
}

